name: 'orgoro'
description: 'coverage'
author: 'orgoro'
inputs:
  coverageFile: 
    required: true
    description: 'local path to a covergae xml file like the output of pytest --cov'
  token: 
    required: true
    description: 'github token'
  thresholdAll:
    required: false
    description: the coverage threshold for average over all files [0,1]
    default: 0.0
  thresholdNew:
    required: false
    description: the coverage threshold for average over new files [0,1]
    default: 0.8
  thresholdModified:
    required: false
    description: the coverage threshold for average over new files [0,1]
    default: 0.0
runs:
  using: 'node12'
  main: 'dist/index.js'
